---
deployment:
  tasks:
    - export TARGET=/home/aadubolc/public_html/xfiles-backend
    - /bin/cp requirements.txt $TARGET
    - /bin/cp passenger_wsgi.py $TARGET
    - /bin/cp manage.py $TARGET
    - /bin/cp .env.production  $TARGET/.env
    - /bin/cp -r accounts $TARGET/
    - /bin/cp -r documents $TARGET/
    - /bin/cp -r media $TARGET/
    - /bin/cp -r ref_table $TARGET/
    - /bin/cp -r static $TARGET/
    - /bin/cp -r staticfiles $TARGET/
    - /bin/cp -r vilco_project $TARGET/
