---
deployment:
  tasks:
    - export TARGET=/home/aadubolc/xfiles_
    
    
    backend
    - /bin/cp requirements.txt $TARGET
    - /bin/cp passenger_wsgi.py $TARGET
    - /bin/cp manage.py $TARGET
    - /bin/cp .env.production  $TARGET/.env
    - /bin/cp -r vilco_project $TARGET/
    - /bin/cp -r accounts $TARGET/
    - /bin/cp -r documents $TARGET/
    - /bin/cp -r ref_table $TARGET/   
    - /bin/mkdir $TARGET/media
    - /bin/mkdir $TARGET/static
#    - /bin/mkdir $TARGET/staticfiles
